version: "3.7"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app


       # ElasticSearch
  elasticsearch:
    container_name: e_shopElasticSearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.4
    environment:
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
    volumes:
      - data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    expose:
      - "9200"
    networks:
      - elastic

  # Kibana
  kibana:
    container_name: e_shopKibana
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:6.8.4
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    expose:
      - "5601"
    networks:
      - elastic

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge
